//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteServicoCadastrar.WSCadastrar {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSCadastrar.CrudServiceSoap")]
    public interface CrudServiceSoap {
        
        // CODEGEN: Generating message contract since element name nome from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cadastrar", ReplyAction="*")]
        ClienteServicoCadastrar.WSCadastrar.CadastrarResponse Cadastrar(ClienteServicoCadastrar.WSCadastrar.CadastrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cadastrar", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteServicoCadastrar.WSCadastrar.CadastrarResponse> CadastrarAsync(ClienteServicoCadastrar.WSCadastrar.CadastrarRequest request);
        
        // CODEGEN: Generating message contract since element name ExcluirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Excluir", ReplyAction="*")]
        ClienteServicoCadastrar.WSCadastrar.ExcluirResponse Excluir(ClienteServicoCadastrar.WSCadastrar.ExcluirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Excluir", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteServicoCadastrar.WSCadastrar.ExcluirResponse> ExcluirAsync(ClienteServicoCadastrar.WSCadastrar.ExcluirRequest request);
        
        // CODEGEN: Generating message contract since element name nome from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alterar", ReplyAction="*")]
        ClienteServicoCadastrar.WSCadastrar.AlterarResponse Alterar(ClienteServicoCadastrar.WSCadastrar.AlterarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alterar", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteServicoCadastrar.WSCadastrar.AlterarResponse> AlterarAsync(ClienteServicoCadastrar.WSCadastrar.AlterarRequest request);
        
        // CODEGEN: Generating message contract since element name ConsultarResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar", ReplyAction="*")]
        ClienteServicoCadastrar.WSCadastrar.ConsultarResponse Consultar(ClienteServicoCadastrar.WSCadastrar.ConsultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteServicoCadastrar.WSCadastrar.ConsultarResponse> ConsultarAsync(ClienteServicoCadastrar.WSCadastrar.ConsultarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CadastrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cadastrar", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicoCadastrar.WSCadastrar.CadastrarRequestBody Body;
        
        public CadastrarRequest() {
        }
        
        public CadastrarRequest(ClienteServicoCadastrar.WSCadastrar.CadastrarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CadastrarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string telefone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string endereco;
        
        public CadastrarRequestBody() {
        }
        
        public CadastrarRequestBody(string nome, string telefone, string endereco) {
            this.nome = nome;
            this.telefone = telefone;
            this.endereco = endereco;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CadastrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CadastrarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicoCadastrar.WSCadastrar.CadastrarResponseBody Body;
        
        public CadastrarResponse() {
        }
        
        public CadastrarResponse(ClienteServicoCadastrar.WSCadastrar.CadastrarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CadastrarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CadastrarResult;
        
        public CadastrarResponseBody() {
        }
        
        public CadastrarResponseBody(string CadastrarResult) {
            this.CadastrarResult = CadastrarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcluirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Excluir", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicoCadastrar.WSCadastrar.ExcluirRequestBody Body;
        
        public ExcluirRequest() {
        }
        
        public ExcluirRequest(ClienteServicoCadastrar.WSCadastrar.ExcluirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExcluirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ExcluirRequestBody() {
        }
        
        public ExcluirRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcluirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExcluirResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicoCadastrar.WSCadastrar.ExcluirResponseBody Body;
        
        public ExcluirResponse() {
        }
        
        public ExcluirResponse(ClienteServicoCadastrar.WSCadastrar.ExcluirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExcluirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExcluirResult;
        
        public ExcluirResponseBody() {
        }
        
        public ExcluirResponseBody(string ExcluirResult) {
            this.ExcluirResult = ExcluirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Alterar", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicoCadastrar.WSCadastrar.AlterarRequestBody Body;
        
        public AlterarRequest() {
        }
        
        public AlterarRequest(ClienteServicoCadastrar.WSCadastrar.AlterarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlterarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string telefone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string endereco;
        
        public AlterarRequestBody() {
        }
        
        public AlterarRequestBody(int id, string nome, string telefone, string endereco) {
            this.id = id;
            this.nome = nome;
            this.telefone = telefone;
            this.endereco = endereco;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlterarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicoCadastrar.WSCadastrar.AlterarResponseBody Body;
        
        public AlterarResponse() {
        }
        
        public AlterarResponse(ClienteServicoCadastrar.WSCadastrar.AlterarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlterarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AlterarResult;
        
        public AlterarResponseBody() {
        }
        
        public AlterarResponseBody(string AlterarResult) {
            this.AlterarResult = AlterarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consultar", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicoCadastrar.WSCadastrar.ConsultarRequestBody Body;
        
        public ConsultarRequest() {
        }
        
        public ConsultarRequest(ClienteServicoCadastrar.WSCadastrar.ConsultarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ConsultarRequestBody() {
        }
        
        public ConsultarRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicoCadastrar.WSCadastrar.ConsultarResponseBody Body;
        
        public ConsultarResponse() {
        }
        
        public ConsultarResponse(ClienteServicoCadastrar.WSCadastrar.ConsultarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteServicoCadastrar.WSCadastrar.Cliente ConsultarResult;
        
        public ConsultarResponseBody() {
        }
        
        public ConsultarResponseBody(ClienteServicoCadastrar.WSCadastrar.Cliente ConsultarResult) {
            this.ConsultarResult = ConsultarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CrudServiceSoapChannel : ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrudServiceSoapClient : System.ServiceModel.ClientBase<ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap>, ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap {
        
        public CrudServiceSoapClient() {
        }
        
        public CrudServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrudServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteServicoCadastrar.WSCadastrar.CadastrarResponse ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap.Cadastrar(ClienteServicoCadastrar.WSCadastrar.CadastrarRequest request) {
            return base.Channel.Cadastrar(request);
        }
        
        public string Cadastrar(string nome, string telefone, string endereco) {
            ClienteServicoCadastrar.WSCadastrar.CadastrarRequest inValue = new ClienteServicoCadastrar.WSCadastrar.CadastrarRequest();
            inValue.Body = new ClienteServicoCadastrar.WSCadastrar.CadastrarRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.telefone = telefone;
            inValue.Body.endereco = endereco;
            ClienteServicoCadastrar.WSCadastrar.CadastrarResponse retVal = ((ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap)(this)).Cadastrar(inValue);
            return retVal.Body.CadastrarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteServicoCadastrar.WSCadastrar.CadastrarResponse> ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap.CadastrarAsync(ClienteServicoCadastrar.WSCadastrar.CadastrarRequest request) {
            return base.Channel.CadastrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteServicoCadastrar.WSCadastrar.CadastrarResponse> CadastrarAsync(string nome, string telefone, string endereco) {
            ClienteServicoCadastrar.WSCadastrar.CadastrarRequest inValue = new ClienteServicoCadastrar.WSCadastrar.CadastrarRequest();
            inValue.Body = new ClienteServicoCadastrar.WSCadastrar.CadastrarRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.telefone = telefone;
            inValue.Body.endereco = endereco;
            return ((ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap)(this)).CadastrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteServicoCadastrar.WSCadastrar.ExcluirResponse ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap.Excluir(ClienteServicoCadastrar.WSCadastrar.ExcluirRequest request) {
            return base.Channel.Excluir(request);
        }
        
        public string Excluir(int id) {
            ClienteServicoCadastrar.WSCadastrar.ExcluirRequest inValue = new ClienteServicoCadastrar.WSCadastrar.ExcluirRequest();
            inValue.Body = new ClienteServicoCadastrar.WSCadastrar.ExcluirRequestBody();
            inValue.Body.id = id;
            ClienteServicoCadastrar.WSCadastrar.ExcluirResponse retVal = ((ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap)(this)).Excluir(inValue);
            return retVal.Body.ExcluirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteServicoCadastrar.WSCadastrar.ExcluirResponse> ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap.ExcluirAsync(ClienteServicoCadastrar.WSCadastrar.ExcluirRequest request) {
            return base.Channel.ExcluirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteServicoCadastrar.WSCadastrar.ExcluirResponse> ExcluirAsync(int id) {
            ClienteServicoCadastrar.WSCadastrar.ExcluirRequest inValue = new ClienteServicoCadastrar.WSCadastrar.ExcluirRequest();
            inValue.Body = new ClienteServicoCadastrar.WSCadastrar.ExcluirRequestBody();
            inValue.Body.id = id;
            return ((ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap)(this)).ExcluirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteServicoCadastrar.WSCadastrar.AlterarResponse ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap.Alterar(ClienteServicoCadastrar.WSCadastrar.AlterarRequest request) {
            return base.Channel.Alterar(request);
        }
        
        public string Alterar(int id, string nome, string telefone, string endereco) {
            ClienteServicoCadastrar.WSCadastrar.AlterarRequest inValue = new ClienteServicoCadastrar.WSCadastrar.AlterarRequest();
            inValue.Body = new ClienteServicoCadastrar.WSCadastrar.AlterarRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.telefone = telefone;
            inValue.Body.endereco = endereco;
            ClienteServicoCadastrar.WSCadastrar.AlterarResponse retVal = ((ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap)(this)).Alterar(inValue);
            return retVal.Body.AlterarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteServicoCadastrar.WSCadastrar.AlterarResponse> ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap.AlterarAsync(ClienteServicoCadastrar.WSCadastrar.AlterarRequest request) {
            return base.Channel.AlterarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteServicoCadastrar.WSCadastrar.AlterarResponse> AlterarAsync(int id, string nome, string telefone, string endereco) {
            ClienteServicoCadastrar.WSCadastrar.AlterarRequest inValue = new ClienteServicoCadastrar.WSCadastrar.AlterarRequest();
            inValue.Body = new ClienteServicoCadastrar.WSCadastrar.AlterarRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.telefone = telefone;
            inValue.Body.endereco = endereco;
            return ((ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap)(this)).AlterarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteServicoCadastrar.WSCadastrar.ConsultarResponse ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap.Consultar(ClienteServicoCadastrar.WSCadastrar.ConsultarRequest request) {
            return base.Channel.Consultar(request);
        }
        
        public ClienteServicoCadastrar.WSCadastrar.Cliente Consultar(int id) {
            ClienteServicoCadastrar.WSCadastrar.ConsultarRequest inValue = new ClienteServicoCadastrar.WSCadastrar.ConsultarRequest();
            inValue.Body = new ClienteServicoCadastrar.WSCadastrar.ConsultarRequestBody();
            inValue.Body.id = id;
            ClienteServicoCadastrar.WSCadastrar.ConsultarResponse retVal = ((ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap)(this)).Consultar(inValue);
            return retVal.Body.ConsultarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteServicoCadastrar.WSCadastrar.ConsultarResponse> ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap.ConsultarAsync(ClienteServicoCadastrar.WSCadastrar.ConsultarRequest request) {
            return base.Channel.ConsultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteServicoCadastrar.WSCadastrar.ConsultarResponse> ConsultarAsync(int id) {
            ClienteServicoCadastrar.WSCadastrar.ConsultarRequest inValue = new ClienteServicoCadastrar.WSCadastrar.ConsultarRequest();
            inValue.Body = new ClienteServicoCadastrar.WSCadastrar.ConsultarRequestBody();
            inValue.Body.id = id;
            return ((ClienteServicoCadastrar.WSCadastrar.CrudServiceSoap)(this)).ConsultarAsync(inValue);
        }

        internal void Consultar(string text)
        {
            throw new NotImplementedException();
        }
    }
}
